# Generated by Django 4.2.7 on 2024-01-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='name',
        ),
    ]
