# Generated by Django 4.2.7 on 2024-01-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_row_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
