# Generated by Django 4.2.7 on 2024-01-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_row_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
