# Generated by Django 4.2.7 on 2024-01-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_row_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.row'),
        ),
    ]
