# Generated by Django 4.2.7 on 2024-01-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_seat_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.row'),
        ),
    ]
