# Generated by Django 4.2.7 on 2024-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_row_row_ticket_price_seat_seat_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='_processing_seats',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
