# Generated by Django 4.2.7 on 2024-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='row_ticket_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_ticket_price',
            field=models.IntegerField(default=0),
        ),
    ]
