# Generated by Django 4.2.7 on 2024-01-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_row_row_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='row_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
