# Generated by Django 4.2.7 on 2024-01-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0015_alter_row_row_ticket_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tickets', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code_path', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.concert')),
                ('selected_seats', models.ManyToManyField(to='booking.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
