# Generated by Django 4.2.7 on 2024-01-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='qr_code_path',
            new_name='qr_file_name',
        ),
    ]
