# Generated by Django 4.2.7 on 2024-01-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_in_cart',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
